### ISSUE TITLE
Segfault when built on Debian 10

### ISSUE THREAD

**Issue by drequivalent** [yukimochi/Activity-Relay#27]
Compilation works fine, but binaries segfault when run.

```
# server 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd5791f]

goroutine 1 [running]:
main.initConfig()
	/root/Activity-Relay/main.go:74 +0x50f
main.main()
	/root/Activity-Relay/main.go:97 +0x26
```
```
# go version
go version go1.11.6 linux/amd64
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# cat ~/Activity-Relay/go.mod 
module github.com/yukimochi/Activity-Relay

go 1.12

require (
	github.com/RichardKnop/machinery v1.6.4
	github.com/Songmu/go-httpdate v1.0.0
	github.com/go-redis/redis v6.15.2+incompatible
	github.com/patrickmn/go-cache v2.1.0+incompatible
	github.com/satori/go.uuid v1.2.0
	github.com/spf13/cobra v0.0.4
	github.com/spf13/viper v1.4.0
	github.com/yukimochi/httpsig v0.1.3
)

replace git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20181218151757-9b75e4fe745a
```

**Comment by drequivalent** [comment]
I see a version mismatch - could it be that?

**Comment by yukimochi** [comment]
The reason of segfault maybe host private key (eg. `actor.pem`) not exist or broken.
